### ISSUE TITLE
Full end to end example

### ISSUE THREAD

**Issue by ThisUsedToBeAnEmail** [michal-josef-spacek/DateTime-Format-PDF#1]
Hey,

Not really an 'issue' just a request, would it be possible to show a full end to end of reading a pdf and then extracting these dates. I think that would be useful for many.

Regards,
Robert.

**Comment by michal-josef-spacek** [comment]
@ThisUsedToBeAnEmail Something like [this](https://github.com/michal-josef-spacek/DateTime-Format-PDF/blob/main/examples/read_dates_from_pdf_builder.pl) and [this](https://github.com/michal-josef-spacek/DateTime-Format-PDF/blob/main/examples/read_dates_from_pdf_api2.pl) ?

**Comment by michal-josef-spacek** [comment]
Examples added to 0.02 release.
